import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import ThemeWiper from "@/components/themeMode/ThemeWiper";
import dynamic from "next/dynamic";
// import Dashborad from "./_dashborad/Dashborad";
const Dashborad = dynamic(() => import("./_dashborad/Dashborad"), {
  ssr: true,
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body>
          <ReduxProvider>
            <ThemeWiper>
              <Dashborad>{children}</Dashborad>
            </ThemeWiper>
          </ReduxProvider>
        </body>
      </html>
  );
}
